CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  "Index" INTEGER,
  "Name" TEXT NOT NULL,
  "Description" TEXT,
  "Brand" TEXT,
  "Category" TEXT,
  "Price" NUMERIC,
  "Currency" TEXT DEFAULT 'USD',
  "Stock" INTEGER,
  "EAN" BIGINT,
  "Color" TEXT,
  "Size" TEXT,
  "Availability" TEXT,
  "ShortDescription" TEXT,
  "Image" TEXT,
  "Internal ID" TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
