CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  index INTEGER,
  name TEXT NOT NULL,
  description TEXT,
  brand TEXT,
  category TEXT,
  price NUMERIC,
  currency TEXT DEFAULT 'USD',
  stock INTEGER,
  ean BIGINT,
  color TEXT,
  size TEXT,
  availability TEXT,
  short_description TEXT,
  image_url TEXT,
  internal_id TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
